/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Backup is the Schema for the backups API */
        Backup: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description BackupSpec defines the desired state of Backup */
            spec: {
                /** @description BackupClassName is the backup tool to use for the backup. */
                backupClassName: string;
                /**
                 * @description Config defines the configuration for the backup job.
                 *     These options are specific to the BackupClass being used and must conform to
                 *     the schema defined in the BackupClass's .spec.config.openAPIV3Schema.
                 */
                config?: Record<string, never>;
                /** @description Destination is the destination for the backup data. */
                destination: {
                    /** @description BackupStorageName is the name of the BackupStorage to use for the backup. */
                    backupStorageName?: string;
                    /** @description S3 contains the S3 information for the backup destination. */
                    s3?: {
                        /**
                         * @description AccessKeyID allows specifying the S3 access key ID inline.
                         *     It is provided as a write-only input field for convenience.
                         *     When this field is set, a webhook writes this value in the Secret specified by `credentialsSecretName`
                         *     and empties this field.
                         *     This field is not stored in the API.
                         */
                        accessKeyId?: string;
                        /** @description Bucket is the name of the S3 bucket. */
                        bucket: string;
                        /**
                         * @description CredentialsSecreName is the reference to the secret containing the S3 credentials.
                         *     The Secret must contain the keys `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
                         */
                        credentialsSecretName: string;
                        /** @description EndpointURL is an endpoint URL of backup storage. */
                        endpointURL: string;
                        /**
                         * @description ForcePathStyle is set to use path-style URLs.
                         *     If unspecified, the default value is false.
                         * @default false
                         */
                        forcePathStyle: boolean;
                        /** @description Region is the region of the S3 bucket. */
                        region: string;
                        /**
                         * @description SecretAccessKey allows specifying the S3 secret access key inline.
                         *     It is provided as a write-only input field for convenience.
                         *     When this field is set, a webhook writes this value in the Secret specified by `credentialsSecretName`
                         *     and empties this field.
                         *     This field is not stored in the API.
                         */
                        secretAccessKey?: string;
                        /**
                         * @description VerifyTLS is set to ensure TLS/SSL verification.
                         *     If unspecified, the default value is true.
                         * @default true
                         */
                        verifyTLS: boolean;
                    };
                };
                /** @description InstanceName is the name of the Instance to back up. */
                instanceName: string;
            };
            /** @description BackupStatus defines the observed state of Backup. */
            status?: {
                /**
                 * Format: date-time
                 * @description CompletedAt is the time when the backup job completed successfully.
                 */
                completedAt?: string;
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
                /** @description JobName is the reference to the job that is running the backup. */
                jobName?: string;
                /**
                 * Format: int64
                 * @description LastObservedGeneration is the last observed generation of the backup job.
                 */
                lastObservedGeneration?: number;
                /** @description Message is the message of the backup job. */
                message?: string;
                /**
                 * Format: date-time
                 * @description StartedAt is the time when the backup job started.
                 */
                startedAt?: string;
                /** @description State is the current state of the backup job. */
                state?: string;
            };
        };
        /** @description BackupClass is the Schema for the backupclasses API */
        BackupClass: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description BackupClassSpec defines the desired state of BackupClass */
            spec: {
                /** @description CleanupJobSpec is the specification of the cleanup job. */
                cleanupJobSpec?: {
                    /** @description Command is the command to run the backup tool. */
                    command?: string[];
                    /** @description Image is the image of the backup tool. */
                    image?: string;
                };
                /**
                 * @description ClusterPermissions defines the cluster-wide permissions required by the backup tool.
                 *     These permissions are used to generate a ClusterRole for the backup job.
                 */
                clusterPermissions?: {
                    /**
                     * @description APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
                     *     the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
                     */
                    apiGroups?: string[];
                    /**
                     * @description NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
                     *     Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
                     *     Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
                     */
                    nonResourceURLs?: string[];
                    /** @description ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed. */
                    resourceNames?: string[];
                    /** @description Resources is a list of resources this rule applies to. '*' represents all resources. */
                    resources?: string[];
                    /** @description Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs. */
                    verbs: string[];
                }[];
                /** @description Config contains additional configuration defined for the backup tool. */
                config?: {
                    /** @description OpenAPIV3Schema is the OpenAPI v3 schema of the backup tool. */
                    openAPIV3Schema?: unknown;
                };
                /**
                 * @description DataStoreConstraints defines compatibility requirements and prerequisites that must be satisfied
                 *     by a DataStore before this backup tool can be used with it. This allows the backup tool to
                 *     express specific requirements about the database configuration needed for successful backup operations,
                 *     such as required database fields, specific engine configurations, or other database properties.
                 *     When a DataStore references this backup tool, the operator will validate the DataStore
                 *     against these constraints before proceeding with the backup operation.
                 */
                dataStoreConstraints?: {
                    /**
                     * @description RequiredFields contains a list of fields that must be set in the DataStore spec.
                     *     Each key is a JSON path expressions that points to a field in the DataStore spec.
                     *     For example, ".spec.engine.type" or ".spec.dataSource.dataImport.config.someField".
                     */
                    requiredFields?: string[];
                };
                /** @description Description is the description of the backup tool. */
                description?: string;
                displayName?: string;
                /** @description JobSpec is the specification of the backup job. */
                jobSpec?: {
                    /** @description Command is the command to run the backup tool. */
                    command?: string[];
                    /** @description Image is the image of the backup tool. */
                    image?: string;
                };
                /**
                 * @description Permissions defines the permissions required by the backup tool.
                 *     These permissions are used to generate a Role for the backup job.
                 */
                permissions?: {
                    /**
                     * @description APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
                     *     the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
                     */
                    apiGroups?: string[];
                    /**
                     * @description NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
                     *     Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
                     *     Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
                     */
                    nonResourceURLs?: string[];
                    /** @description ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed. */
                    resourceNames?: string[];
                    /** @description Resources is a list of resources this rule applies to. '*' represents all resources. */
                    resources?: string[];
                    /** @description Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs. */
                    verbs: string[];
                }[];
                /** @description SupportedProviders is the list of providers that the backup tool supports. */
                supportedProviders?: string[];
            };
            /** @description BackupClassStatus defines the observed state of BackupClass. */
            status?: {
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
            };
        };
        /** @description BackupClassList is an object that contains the list of the existing backupclasss. */
        BackupClassList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["BackupClass"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
            };
        };
        /** @description BackupList is an object that contains the list of the existing backups. */
        BackupList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["Backup"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
                /** @description Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
                namespace?: string;
            };
        };
        /** @description Instance is the Schema for the instances API */
        Instance: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description InstanceSpec defines the desired state of Instance */
            spec: {
                /**
                 * @description Components defines the component instances for this cluster.
                 *     The keys are component names (e.g., "engine", "proxy", "backupAgent").
                 *     Which components are valid depends on the selected topology.
                 */
                components?: {
                    [key: string]: {
                        /** @description Config specifies the component specific configuration. */
                        config?: {
                            /**
                             * @description LocalObjectReference contains enough information to let you locate the
                             *     referenced object inside the same namespace.
                             */
                            configMapRef?: {
                                /**
                                 * @description Name of the referent.
                                 *     This field is effectively required, but due to backwards compatibility is
                                 *     allowed to be empty. Instances of this type with an empty value here are
                                 *     almost certainly wrong.
                                 *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                 * @default
                                 */
                                name: string;
                            };
                            key?: string;
                            /**
                             * @description LocalObjectReference contains enough information to let you locate the
                             *     referenced object inside the same namespace.
                             */
                            secretRef?: {
                                /**
                                 * @description Name of the referent.
                                 *     This field is effectively required, but due to backwards compatibility is
                                 *     allowed to be empty. Instances of this type with an empty value here are
                                 *     almost certainly wrong.
                                 *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                 * @default
                                 */
                                name: string;
                            };
                        };
                        /**
                         * @description CustomSpec provides an API for customising this component.
                         *     The API schema is defined by the provider's ComponentSchemas.
                         */
                        customSpec?: Record<string, never>;
                        /**
                         * @description Image specifies an override for the image to use.
                         *     When unspecified, it is autmatically set from the ComponentVersions
                         *     based on the Version specified.
                         */
                        image?: string;
                        /** @description Name of the component. */
                        name?: string;
                        /**
                         * Format: int32
                         * @description Replicas specifies the number of replicas for this component.
                         */
                        replicas?: number;
                        /** @description Resources requirements for this component. */
                        resources?: {
                            /**
                             * @description Claims lists the names of resources, defined in spec.resourceClaims,
                             *     that are used by this container.
                             *
                             *     This field depends on the
                             *     DynamicResourceAllocation feature gate.
                             *
                             *     This field is immutable. It can only be set for containers.
                             */
                            claims?: {
                                /**
                                 * @description Name must match the name of one entry in pod.spec.resourceClaims of
                                 *     the Pod where this field is used. It makes that resource available
                                 *     inside a container.
                                 */
                                name: string;
                                /**
                                 * @description Request is the name chosen for a request in the referenced claim.
                                 *     If empty, everything from the claim is made available, otherwise
                                 *     only the result of this request.
                                 */
                                request?: string;
                            }[];
                            /**
                             * @description Limits describes the maximum amount of compute resources allowed.
                             *     More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                             */
                            limits?: {
                                [key: string]: number | string;
                            };
                            /**
                             * @description Requests describes the minimum amount of compute resources required.
                             *     If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
                             *     otherwise to an implementation-defined value. Requests cannot exceed Limits.
                             *     More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                             */
                            requests?: {
                                [key: string]: number | string;
                            };
                        };
                        /**
                         * @description Storage requirements for this component.
                         *     For stateless components, this is an optional field.
                         */
                        storage?: {
                            size?: number | string;
                            storageClass?: string;
                        };
                        /** @description Type of the component from the Provider. */
                        type?: string;
                        /** @description Version of the component from ComponentVersions. */
                        version?: string;
                    };
                };
                /**
                 * @description Global contains provider-level configuration that applies to the entire cluster.
                 *     The schema for this field is defined by the provider's GlobalConfigSchema.
                 */
                global?: Record<string, never>;
                /** @description Provider is the name of the database provider (e.g., "psmdb", "postgresql"). */
                provider?: string;
                /** @description Topology defines the deployment topology and its configuration. */
                topology?: {
                    /**
                     * @description Config contains topology-specific configuration.
                     *     The schema for this field is defined by the provider's TopologyDefinition.
                     *     Examples: shard count for sharded topology, replication factor, etc.
                     */
                    config?: Record<string, never>;
                    /**
                     * @description Type is the topology name (e.g., "sharded", "replicaset").
                     *     The available topologies are defined by the provider.
                     *     If omitted, the provider's default topology is used.
                     */
                    type?: string;
                };
                /**
                 * @description Version selects a provider-defined version bundle, resolving compatible
                 *     versions for all components automatically. Per-component versions set
                 *     in Components take precedence over the bundle.
                 *     If omitted and the provider defines a default bundle, that bundle is used.
                 */
                version?: string;
            };
            /** @description InstanceStatus defines the observed state of Instance. */
            status?: {
                /** @description Components is the status of the components in the database cluster. */
                components?: {
                    pods?: {
                        /**
                         * @description Name of the referent.
                         *     This field is effectively required, but due to backwards compatibility is
                         *     allowed to be empty. Instances of this type with an empty value here are
                         *     almost certainly wrong.
                         *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                         * @default
                         */
                        name: string;
                    }[];
                    /** Format: int32 */
                    ready?: number;
                    state?: string;
                    /** Format: int32 */
                    total?: number;
                }[];
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
                /**
                 * @description ConnectionSecretRef is a reference to the Secret containing connection details.
                 *     The Secret is auto-generated by the provider-runtime reconciler with the name
                 *     "{instance-name}-conn" and owned by the Instance (auto-deleted on cleanup).
                 *
                 *     The Secret uses well-known keys inspired by the Service Binding specification:
                 *       - "type"     - Database type (e.g., "mongodb", "postgresql")
                 *       - "provider" - Provider name (e.g., "percona-server-mongodb")
                 *       - "host"     - Hostname or IP address
                 *       - "port"     - Port number
                 *       - "username" - Database username
                 *       - "password" - Database password
                 *       - "uri"      - Full connection URI including credentials
                 */
                connectionSecretRef?: {
                    /**
                     * @description Name of the referent.
                     *     This field is effectively required, but due to backwards compatibility is
                     *     allowed to be empty. Instances of this type with an empty value here are
                     *     almost certainly wrong.
                     *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                     * @default
                     */
                    name: string;
                };
                /**
                 * @description Phase of the database cluster.
                 * @enum {string}
                 */
                phase?: "Pending" | "Provisioning" | "Initializing" | "Ready" | "Updating" | "Terminating" | "Failed" | "Restoring" | "Suspending" | "Suspended" | "Resuming";
                /**
                 * @description Version is the effective version bundle that is currently applied to this
                 *     Instance. On the first reconciliation the provider-runtime writes the
                 *     resolved default bundle name here and uses this value on every subsequent
                 *     reconciliation when spec.version is empty. This ensures that a Provider
                 *     upgrade (which may change the default bundle) never silently triggers an
                 *     unintended database upgrade on existing Instances.
                 *
                 *     GitOps tools (ArgoCD, Flux) exclude status from diff calculations by
                 *     default, so this field does not cause spurious out-of-sync alerts.
                 */
                version?: string;
            };
        };
        /** @description ConnectionDetails holds the typed connection details for a database instance. These are written by the provider-runtime reconciler to a Kubernetes Secret and later read back by the API server to serve the connection endpoint. They follow the Service Binding well-known keys where applicable. */
        InstanceConnectionDetails: {
            /** @description Host is the hostname or IP address to connect to */
            host?: string;
            /** @description Password is the password for authentication */
            password?: string;
            /** @description Port is the port number to connect to */
            port?: string;
            /** @description Provider is the provider that manages this instance */
            provider?: string;
            /** @description Type is the type of database (e.g., mongodb, postgresql, mysql) */
            type?: string;
            /** @description URI is a pre-built connection URI */
            uri?: string;
            /** @description Username is the username for authentication */
            username?: string;
        } & {
            [key: string]: string;
        };
        /** @description InstanceList is an object that contains the list of the existing instances. */
        InstanceList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["Instance"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
                /** @description Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
                namespace?: string;
            };
        };
        /** @description MonitoringConfig is the Schema for the monitoringconfigs API. */
        MonitoringConfig: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description spec defines the desired state of MonitoringConfig */
            spec: {
                /**
                 * @description CredentialsSecretName is the reference to the secret containing the API key.
                 *     It contains `apiKey` key with the API key value.
                 */
                credentialsSecretName: string;
                /**
                 * @description Type is the name of monitoring tool (e.g., "pmm").
                 * @enum {string}
                 */
                type: "pmm";
                /** @description URL is the URL of the monitoring server (e.g., PMM server URL). */
                url: string;
                /**
                 * @description VerifyTLS is set to ensure TLS/SSL verification.
                 *     If unspecified, the default value is true.
                 * @default true
                 */
                verifyTLS: boolean;
            };
            /**
             * @description status defines the observed state of MonitoringConfig
             * @default {
             *       "inUse": false
             *     }
             */
            status: {
                /**
                 * @description InUse is a flag that indicates if any Instance uses the monitoring config.
                 * @default false
                 */
                inUse: boolean;
                /**
                 * Format: int64
                 * @description LastObservedGeneration is the most recent generation observed for this MonitoringConfig.
                 */
                lastObservedGeneration?: number;
                /** @description PMMServerVersion shows PMM server version. */
                pmmServerVersion?: string;
            };
        };
        /** @description MonitoringConfigList is an object that contains the list of the existing monitoringconfigs. */
        MonitoringConfigList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["MonitoringConfig"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
                /** @description Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
                namespace?: string;
            };
        };
        /** @description Provider is the Schema for the providers API */
        Provider: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description ProviderSpec defines the desired state of Provider */
            spec: {
                componentTypes?: {
                    [key: string]: {
                        versions?: {
                            default?: boolean;
                            image?: string;
                            version?: string;
                        }[];
                    };
                };
                components?: {
                    [key: string]: {
                        /** @description CustomSpecSchema holds the OpenAPI v3 schema for this component's CustomSpec. */
                        customSpecSchema?: Record<string, never>;
                        type?: string;
                    };
                };
                /** @description GlobalConfigSchema holds the OpenAPI v3 schema for the global configuration. */
                globalConfigSchema?: Record<string, never>;
                topologies?: {
                    [key: string]: {
                        components?: {
                            [key: string]: {
                                optional?: boolean;
                            };
                        };
                        /** @description ConfigSchema holds the OpenAPI v3 schema for topology-specific configuration. */
                        configSchema?: Record<string, never>;
                    };
                };
                /** @description UISchema holds the UI rendering hints for each topology. */
                uiSchema?: Record<string, never>;
                /**
                 * @description Versions defines curated version bundles — named sets of component
                 *     versions that are known to be mutually compatible. Users reference
                 *     a bundle via Instance.Spec.Version. If the user does not set a version,
                 *     the bundle whose Default field is true is used automatically.
                 */
                versions?: {
                    /**
                     * @description Components maps component names to their version strings for this bundle.
                     *     Keys must match component names defined in ProviderSpec.Components.
                     */
                    components?: {
                        [key: string]: string;
                    };
                    /**
                     * @description Default marks this bundle as the implicit choice when an Instance omits
                     *     Spec.Version entirely. Exactly one bundle should have Default: true.
                     */
                    default?: boolean;
                    /**
                     * @description Name is the unique identifier for this bundle (e.g. "8.0.12").
                     *     Users set Instance.Spec.Version to this value to select the bundle.
                     */
                    name: string;
                }[];
            };
            /** @description ProviderStatus defines the observed state of Provider. */
            status?: {
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
            };
        };
        /** @description ProviderList is an object that contains the list of the existing providers. */
        ProviderList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["Provider"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
