package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
)

const generatedFileTemplate = `// Code generated by gen-rbac-resources. DO NOT EDIT.

package rbac

// AllResources is a list of all resource names extracted from the API specification.
var AllResources = []string{
{{- range .Resources}}
	"{{.}}",
{{- end}}
}

// resourcePathMap maps API paths to their resource names.
// Paths use colon notation for parameters (e.g., "/:namespace/clusters").
var resourcePathMap = map[string]string{
{{- range .PathMappings}}
	"{{.Path}}": "{{.Resource}}",
{{- end}}
}

// skipPaths lists API paths that should skip RBAC checks.
var skipPaths = []string{
{{- range .SkipPaths}}
	"{{.}}",
{{- end}}
}

// GetResourcePathMap returns a copy of the resource path map with an optional base path prefix.
func GetResourcePathMap(basePath string) map[string]string {
	result := make(map[string]string, len(resourcePathMap))
	for path, resource := range resourcePathMap {
		result[basePath+path] = resource
	}
	return result
}

// GetSkipPaths returns a copy of the skip paths with an optional base path prefix.
func GetSkipPaths(basePath string) []string {
	result := make([]string, len(skipPaths))
	for i, path := range skipPaths {
		result[i] = basePath + path
	}
	return result
}
`

type PathMapping struct {
	Path     string
	Resource string
}

type TemplateData struct {
	Resources    []string
	PathMappings []PathMapping
	SkipPaths    []string
}

func main() {
	specFile := flag.String("spec", "api/openapi/http-api.yaml", "Path to OpenAPI specification file")
	outputFile := flag.String("output", "pkg/rbac/resources.gen.go", "Output Go file")
	resourceNameExt := flag.String("resource-ext", "x-everest-resource-name", "OpenAPI extension field for resource names")
	flag.Parse()

	if err := run(*specFile, *outputFile, *resourceNameExt); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(specFile, outputFile, resourceNameExt string) error {
	// Load the OpenAPI specification
	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	doc, err := loader.LoadFromFile(specFile)
	if err != nil {
		return fmt.Errorf("failed to load OpenAPI spec: %w", err)
	}

	// Extract resource information
	resourceSet := make(map[string]bool)
	pathMappings := []PathMapping{}
	skipPaths := []string{}

	// parseEndpoint converts OpenAPI path parameters to colon notation
	parseEndpoint := func(path string) string {
		parsed := strings.ReplaceAll(path, "{", ":")
		parsed = strings.ReplaceAll(parsed, "}", "")
		return parsed
	}

	for path, pathItem := range doc.Paths.Map() {
		parsedPath := parseEndpoint(path)

		// Check for resource name extension
		if val, ok := pathItem.Extensions[resourceNameExt]; ok {
			if resourceName, ok := val.(string); ok {
				resourceSet[resourceName] = true
				pathMappings = append(pathMappings, PathMapping{
					Path:     parsedPath,
					Resource: resourceName,
				})
				continue
			}
		}

		// Path has no resource name, add to skip list
		skipPaths = append(skipPaths, parsedPath)
	}

	// Convert resource set to sorted slice
	resources := make([]string, 0, len(resourceSet))
	for resource := range resourceSet {
		resources = append(resources, resource)
	}
	sort.Strings(resources)
	sort.Slice(pathMappings, func(i, j int) bool {
		return pathMappings[i].Path < pathMappings[j].Path
	})
	sort.Strings(skipPaths)

	// Generate the Go file
	tmpl := template.Must(template.New("generated").Parse(generatedFileTemplate))

	data := TemplateData{
		Resources:    resources,
		PathMappings: pathMappings,
		SkipPaths:    skipPaths,
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to generate Go code: %w", err)
	}

	fmt.Printf("Successfully generated RBAC resources file: %s\n", outputFile)
	fmt.Printf("  - %d unique resources\n", len(resources))
	fmt.Printf("  - %d path mappings\n", len(pathMappings))
	fmt.Printf("  - %d skip paths\n", len(skipPaths))

	return nil
}
