#!/bin/bash

## ===== General environment variables for the Controller tests =====
export OPENEVEREST_ROOT_PATH=${OPENEVEREST_ROOT_PATH:-${PWD}}
echo "OPENEVEREST_ROOT_PATH=${OPENEVEREST_ROOT_PATH}"

export VICTORIAMETRICS_OPERATOR_VERSION=${VICTORIAMETRICS_OPERATOR_VERSION:-"0.66.1"}
echo "VICTORIAMETRICS_OPERATOR_VERSION=${VICTORIAMETRICS_OPERATOR_VERSION}"
