---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-monitoring-openeverest-io-v1alpha2-monitoringconfig
  failurePolicy: Fail
  name: vmonitoringconfig-v1alpha2.kb.io
  rules:
  - apiGroups:
    - monitoring.openeverest.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - monitoringconfigs
  sideEffects: None
