#!/usr/bin/env python3
"""
Copyright header tool for the OpenEverest project.

Rules:
  1. File already has the OpenEverest copyright line → skip (idempotent).
  2. File has any Percona copyright line (any year / year-range variant) →
     insert the OpenEverest line immediately after that line.
  3. File has no copyright at all → prepend a full Apache 2.0 header with
     only the OpenEverest copyright.

Supported extensions: .go  .ts  .tsx

Exit codes:
    check mode:
        0 – all checked files have the required header
        1 – one or more files are missing the required header
        2 – processing error
    fix mode:
        0 – completed successfully (with or without updates)
        2 – processing error
"""

import argparse
import os
import re
import fnmatch
import subprocess
import sys
from datetime import date
from typing import List

YEAR = str(date.today().year)

OE_COPYRIGHT_LINE = f"// Copyright (C) {YEAR} The OpenEverest Contributors"

# Matches any Percona copyright variant, e.g.:
#   // Copyright (C) 2023 Percona LLC
#   // Copyright (C) 2023-2025 Percona LLC
#   // Copyright (C) 2023 Percona
PERCONA_RE = re.compile(r"^// Copyright \(C\) [\d]{4}(?:-[\d]{4})? Percona.*$", re.MULTILINE)

# Check whether the file already carries the OpenEverest line (any year).
OE_PRESENT_RE = re.compile(r"// Copyright \(C\) [\d]{4} The OpenEverest Contributors")

NEW_FILE_HEADER = f"""\
// Copyright (C) {YEAR} The OpenEverest Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
"""

SUPPORTED_EXTENSIONS = {".go", ".ts", ".tsx"}
IGNORE_FILE_NAME = ".copyrightignore"
AUTO_GENERATED_MARKERS = (
    "This file was auto-generated",
    "Code generated by",
)


class FileStatus:
    """File processing result constants."""

    OK = "ok"
    MISSING = "missing"
    UPDATED = "updated"
    ERROR = "error"


def get_repo_root() -> str:
    """Return git repo root or the current working directory as fallback."""
    try:
        output = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return os.getcwd()
    return output or os.getcwd()


def load_ignore_patterns(repo_root: str) -> List[str]:
    """Load ignore patterns from .copyrightignore if it exists."""
    ignore_path = os.path.join(repo_root, IGNORE_FILE_NAME)
    if not os.path.isfile(ignore_path):
        return []

    patterns: List[str] = []
    try:
        with open(ignore_path, encoding="utf-8") as fh:
            for line in fh:
                pattern = line.strip()
                if not pattern or pattern.startswith("#"):
                    continue
                patterns.append(pattern)
    except OSError as exc:
        print(f"WARNING: could not read {ignore_path}: {exc}", file=sys.stderr)
        return []

    return patterns


def path_is_ignored(filepath: str, repo_root: str, patterns: List[str]) -> bool:
    """Check if a file path matches any ignore pattern."""
    rel_path = os.path.relpath(os.path.abspath(filepath), repo_root).replace(os.sep, "/")

    for raw_pattern in patterns:
        pattern = raw_pattern.replace("\\", "/")
        if pattern.startswith("/"):
            pattern = pattern.lstrip("/")
        if pattern.endswith("/"):
            pattern = f"{pattern}**"

        if fnmatch.fnmatch(rel_path, pattern):
            return True

        # Non-rooted patterns can also match at any subpath depth.
        if not raw_pattern.startswith("/") and fnmatch.fnmatch(rel_path, f"**/{pattern}"):
            return True

    return False


def process_file(filepath: str, repo_root: str, ignore_patterns: List[str], check_only: bool) -> str:
    """Process a file and return a FileStatus value."""
    if path_is_ignored(filepath, repo_root, ignore_patterns):
        return FileStatus.OK

    try:
        with open(filepath, encoding="utf-8") as fh:
            content = fh.read()
    except (OSError, UnicodeDecodeError) as exc:
        print(f"WARNING: could not read {filepath}: {exc}", file=sys.stderr)
        return FileStatus.ERROR

    if any(marker in content for marker in AUTO_GENERATED_MARKERS):
        return FileStatus.OK

    # Rule 1 – already up-to-date.
    if OE_PRESENT_RE.search(content):
        return FileStatus.OK

    if check_only:
        return FileStatus.MISSING

    percona_match = PERCONA_RE.search(content)

    if percona_match:
        # Rule 2 – insert OE line right after the matched Percona line.
        insert_pos = percona_match.end()
        new_content = content[:insert_pos] + "\n" + OE_COPYRIGHT_LINE + content[insert_pos:]
    else:
        # Rule 3 – no existing copyright; prepend the full header.
        # Keep one blank line between the new header and the existing content.
        new_content = NEW_FILE_HEADER + "\n" + content.lstrip("\n")

    try:
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(new_content)
    except OSError as exc:
        print(f"WARNING: could not write {filepath}: {exc}", file=sys.stderr)
        return FileStatus.ERROR

    print(f"Updated: {filepath}")
    return FileStatus.UPDATED


def iter_files(paths: list[str]):
    """Yield file paths, expanding directories recursively."""
    for path in paths:
        if os.path.isdir(path):
            for root, _, files in os.walk(path):
                for name in files:
                    yield os.path.join(root, name)
        elif os.path.isfile(path):
            yield path


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Check or add copyright headers for source files.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check only. Exit 1 if files are missing headers.",
    )
    parser.add_argument(
        "--paths-nul-file",
        help="Read additional paths from a NUL-delimited file.",
    )
    parser.add_argument("paths", nargs="*", help="File or directory paths to process.")
    return parser.parse_args()


def read_paths_from_nul_file(file_path: str) -> list[str]:
    """Read NUL-delimited paths from file."""
    try:
        with open(file_path, "rb") as fh:
            data = fh.read()
    except OSError as exc:
        print(f"ERROR: could not read path list file {file_path}: {exc}", file=sys.stderr)
        raise

    if not data:
        return []

    return [entry.decode("utf-8") for entry in data.split(b"\0") if entry]


def main() -> None:
    args = parse_args()

    paths = list(args.paths)
    if args.paths_nul_file:
        try:
            paths.extend(read_paths_from_nul_file(args.paths_nul_file))
        except OSError:
            sys.exit(2)

    if not paths:
        print("Usage: add_copyright.py [--check] <file-or-dir> [...]")
        sys.exit(0)

    repo_root = get_repo_root()
    ignore_patterns = load_ignore_patterns(repo_root)

    seen_paths: set[str] = set()
    modified: list[str] = []
    missing: list[str] = []
    errors = 0

    for filepath in iter_files(paths):
        if os.path.splitext(filepath)[1] in SUPPORTED_EXTENSIONS:
            normalized = os.path.abspath(filepath)
            if normalized in seen_paths:
                continue
            seen_paths.add(normalized)

            status = process_file(filepath, repo_root, ignore_patterns, args.check)
            if status == FileStatus.UPDATED:
                modified.append(filepath)
            elif status == FileStatus.MISSING:
                missing.append(filepath)
            elif status == FileStatus.ERROR:
                errors += 1

    if args.check:
        if missing:
            print("Files missing copyright headers:")
            for path in missing:
                print(path)
            print(f"\n{len(missing)} file(s) require headers.")

        if errors:
            print(f"\nEncountered {errors} file processing error(s).", file=sys.stderr)
            sys.exit(2)

        if missing:
            sys.exit(1)

        print("All checked files contain the required copyright headers.")
        sys.exit(0)

    if modified:
        print(f"\n{len(modified)} file(s) updated.")

    if errors:
        print(f"\nEncountered {errors} file processing error(s).", file=sys.stderr)
        sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
