// Code generated by gen-rbac-resources. DO NOT EDIT.

package rbac

// AllResources is a list of all resource names extracted from the API specification.
var AllResources = []string{
	"backup-classes",
	"backup-storages",
	"backups",
	"data-import-jobs",
	"data-importers",
	"database-cluster-backups",
	"database-cluster-credentials",
	"database-cluster-restores",
	"database-clusters",
	"database-engines",
	"enginefeatures/split-horizon-dns-configs",
	"instances",
	"load-balancer-configs",
	"monitoring-instances",
	"namespaces",
	"pod-scheduling-policies",
	"providers",
}

// resourcePathMap maps API paths to their resource names.
// Paths use colon notation for parameters (e.g., "/:namespace/clusters").
var resourcePathMap = map[string]string{
	"/clusters/:cluster/backup-classes":                                              "backup-classes",
	"/clusters/:cluster/backup-classes/:backupClass":                                 "backup-classes",
	"/clusters/:cluster/namespaces/:namespace/backups":                               "backups",
	"/clusters/:cluster/namespaces/:namespace/backups/:backup":                       "backups",
	"/clusters/:cluster/namespaces/:namespace/instances":                             "instances",
	"/clusters/:cluster/namespaces/:namespace/instances/:instance":                   "instances",
	"/clusters/:cluster/namespaces/:namespace/instances/:instance/connection":        "instances",
	"/clusters/:cluster/providers":                                                   "providers",
	"/clusters/:cluster/providers/:provider":                                         "providers",
	"/data-importers":                                                                "data-importers",
	"/load-balancer-configs":                                                         "load-balancer-configs",
	"/load-balancer-configs/:config-name":                                            "load-balancer-configs",
	"/namespaces":                                                                    "namespaces",
	"/namespaces/:namespace/backup-storages":                                         "backup-storages",
	"/namespaces/:namespace/backup-storages/:name":                                   "backup-storages",
	"/namespaces/:namespace/database-cluster-backups":                                "database-cluster-backups",
	"/namespaces/:namespace/database-cluster-backups/:name":                          "database-cluster-backups",
	"/namespaces/:namespace/database-cluster-restores":                               "database-cluster-restores",
	"/namespaces/:namespace/database-cluster-restores/:name":                         "database-cluster-restores",
	"/namespaces/:namespace/database-clusters":                                       "database-clusters",
	"/namespaces/:namespace/database-clusters/:cluster-name/backups":                 "database-cluster-backups",
	"/namespaces/:namespace/database-clusters/:cluster-name/restores":                "database-cluster-restores",
	"/namespaces/:namespace/database-clusters/:dbName/data-import-jobs":              "data-import-jobs",
	"/namespaces/:namespace/database-clusters/:name":                                 "database-clusters",
	"/namespaces/:namespace/database-clusters/:name/components":                      "database-clusters",
	"/namespaces/:namespace/database-clusters/:name/components/:component_name/logs": "database-clusters",
	"/namespaces/:namespace/database-clusters/:name/credentials":                     "database-cluster-credentials",
	"/namespaces/:namespace/database-clusters/:name/pitr":                            "database-clusters",
	"/namespaces/:namespace/database-engines":                                        "database-engines",
	"/namespaces/:namespace/database-engines/:name":                                  "database-engines",
	"/namespaces/:namespace/database-engines/upgrade-plan":                           "database-engines",
	"/namespaces/:namespace/database-engines/upgrade-plan/approval":                  "database-engines",
	"/namespaces/:namespace/engine-features/split-horizon-dns-configs":               "enginefeatures/split-horizon-dns-configs",
	"/namespaces/:namespace/engine-features/split-horizon-dns-configs/:name":         "enginefeatures/split-horizon-dns-configs",
	"/namespaces/:namespace/monitoring-instances":                                    "monitoring-instances",
	"/namespaces/:namespace/monitoring-instances/:name":                              "monitoring-instances",
	"/pod-scheduling-policies":                                                       "pod-scheduling-policies",
	"/pod-scheduling-policies/:policy-name":                                          "pod-scheduling-policies",
}

// skipPaths lists API paths that should skip RBAC checks.
var skipPaths = []string{
	"/cluster-info",
	"/clusters",
	"/clusters/:name",
	"/namespaces/:namespace/database-clusters/:dbName/secret",
	"/permissions",
	"/resources",
	"/session",
	"/settings",
	"/version",
}

// GetResourcePathMap returns a copy of the resource path map with an optional base path prefix.
func GetResourcePathMap(basePath string) map[string]string {
	result := make(map[string]string, len(resourcePathMap))
	for path, resource := range resourcePathMap {
		result[basePath+path] = resource
	}
	return result
}

// GetSkipPaths returns a copy of the skip paths with an optional base path prefix.
func GetSkipPaths(basePath string) []string {
	result := make([]string, len(skipPaths))
	for i, path := range skipPaths {
		result[i] = basePath + path
	}
	return result
}
