// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Backup Backup is the schema for the backup job API.
type Backup struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec BackupSpec defines the desired state of Backup.
	Spec *struct {
		// BackupClassName BackupClassName is the backup tool to use for the backup.
		BackupClassName string `json:"backupClassName"`

		// Config Config defines the configuration for the backup job.
		// These options are specific to the BackupClass being used and must conform to
		// the schema defined in the BackupClass's .spec.config.openAPIV3Schema.
		Config *map[string]interface{} `json:"config,omitempty"`

		// Destination Destination is the destination for the backup data.
		Destination struct {
			// BackupStorageName BackupStorageName is the name of the BackupStorage to use for the backup.
			BackupStorageName *string `json:"backupStorageName,omitempty"`

			// S3 S3 contains the S3 information for the backup destination.
			S3 *struct {
				// AccessKeyId AccessKeyID allows specifying the S3 access key ID inline.
				// It is provided as a write-only input field for convenience.
				// When this field is set, a webhook writes this value in the Secret specified by `credentialsSecretName`
				// and empties this field.
				// This field is not stored in the API.
				AccessKeyId *string `json:"accessKeyId,omitempty"`

				// Bucket Bucket is the name of the S3 bucket.
				Bucket string `json:"bucket"`

				// CredentialsSecretName CredentialsSecreName is the reference to the secret containing the S3 credentials.
				// The Secret must contain the keys `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
				CredentialsSecretName string `json:"credentialsSecretName"`

				// EndpointURL EndpointURL is an endpoint URL of backup storage.
				EndpointURL string `json:"endpointURL"`

				// ForcePathStyle ForcePathStyle is set to use path-style URLs.
				// If unspecified, the default value is false.
				ForcePathStyle *bool `json:"forcePathStyle,omitempty"`

				// Region Region is the region of the S3 bucket.
				Region string `json:"region"`

				// SecretAccessKey SecretAccessKey allows specifying the S3 secret access key inline.
				// It is provided as a write-only input field for convenience.
				// When this field is set, a webhook writes this value in the Secret specified by `credentialsSecretName`
				// and empties this field.
				// This field is not stored in the API.
				SecretAccessKey *string `json:"secretAccessKey,omitempty"`

				// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
				// If unspecified, the default value is true.
				VerifyTLS *bool `json:"verifyTLS,omitempty"`
			} `json:"s3,omitempty"`
		} `json:"destination"`

		// InstanceName InstanceName is the name of the Instance to back up.
		InstanceName string `json:"instanceName"`
	} `json:"spec,omitempty"`

	// Status BackupStatus defines the observed state of Backup.
	Status *struct {
		// CompletedAt CompletedAt is the time when the backup job completed successfully.
		CompletedAt *time.Time `json:"completedAt,omitempty"`

		// JobName JobName is the reference to the job that is running the backup.
		JobName *string `json:"jobName,omitempty"`

		// LastObservedGeneration LastObservedGeneration is the last observed generation of the backup job.
		LastObservedGeneration *int64 `json:"lastObservedGeneration,omitempty"`

		// Message Message is the message of the backup job.
		Message *string `json:"message,omitempty"`

		// StartedAt StartedAt is the time when the backup job started.
		StartedAt *time.Time `json:"startedAt,omitempty"`

		// State State is the current state of the backup job.
		State *string `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// BackupClass BackupClass defines a reusable strategy for backing up data from a DataStore.
type BackupClass struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec BackupClassSpec defines the specification of a BackupClass.
	Spec *struct {
		// CleanupJobSpec CleanupJobSpec is the specification of the cleanup job.
		CleanupJobSpec *struct {
			// Command Command is the command to run the backup tool.
			Command *[]string `json:"command,omitempty"`

			// Image Image is the image of the backup tool.
			Image *string `json:"image,omitempty"`
		} `json:"cleanupJobSpec,omitempty"`

		// ClusterPermissions ClusterPermissions defines the cluster-wide permissions required by the backup tool.
		// These permissions are used to generate a ClusterRole for the backup job.
		ClusterPermissions *[]struct {
			// ApiGroups APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
			// the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
			ApiGroups *[]string `json:"apiGroups,omitempty"`

			// NonResourceURLs NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
			// Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
			// Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
			NonResourceURLs *[]string `json:"nonResourceURLs,omitempty"`

			// ResourceNames ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.
			ResourceNames *[]string `json:"resourceNames,omitempty"`

			// Resources Resources is a list of resources this rule applies to. '*' represents all resources.
			Resources *[]string `json:"resources,omitempty"`

			// Verbs Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs.
			Verbs []string `json:"verbs"`
		} `json:"clusterPermissions,omitempty"`

		// Config Config contains additional configuration defined for the backup tool.
		Config *struct {
			// OpenAPIV3Schema OpenAPIV3Schema is the OpenAPI v3 schema of the backup tool.
			OpenAPIV3Schema interface{} `json:"openAPIV3Schema,omitempty"`
		} `json:"config,omitempty"`

		// DataStoreConstraints DataStoreConstraints defines compatibility requirements and prerequisites that must be satisfied
		// by a DataStore before this backup tool can be used with it. This allows the backup tool to
		// express specific requirements about the database configuration needed for successful backup operations,
		// such as required database fields, specific engine configurations, or other database properties.
		// When a DataStore references this backup tool, the operator will validate the DataStore
		// against these constraints before proceeding with the backup operation.
		DataStoreConstraints *struct {
			// RequiredFields RequiredFields contains a list of fields that must be set in the DataStore spec.
			// Each key is a JSON path expressions that points to a field in the DataStore spec.
			// For example, ".spec.engine.type" or ".spec.dataSource.dataImport.config.someField".
			RequiredFields *[]string `json:"requiredFields,omitempty"`
		} `json:"dataStoreConstraints,omitempty"`

		// Description Description is the description of the backup tool.
		Description *string `json:"description,omitempty"`

		// DisplayName DisplayName is a human-readable name for the backup tool.
		DisplayName *string `json:"displayName,omitempty"`

		// JobSpec JobSpec is the specification of the backup job.
		JobSpec *struct {
			// Command Command is the command to run the backup tool.
			Command *[]string `json:"command,omitempty"`

			// Image Image is the image of the backup tool.
			Image *string `json:"image,omitempty"`
		} `json:"jobSpec,omitempty"`

		// Permissions Permissions defines the permissions required by the backup tool.
		// These permissions are used to generate a Role for the backup job.
		Permissions *[]struct {
			// ApiGroups APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
			// the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
			ApiGroups *[]string `json:"apiGroups,omitempty"`

			// NonResourceURLs NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
			// Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
			// Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
			NonResourceURLs *[]string `json:"nonResourceURLs,omitempty"`

			// ResourceNames ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.
			ResourceNames *[]string `json:"resourceNames,omitempty"`

			// Resources Resources is a list of resources this rule applies to. '*' represents all resources.
			Resources *[]string `json:"resources,omitempty"`

			// Verbs Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs.
			Verbs []string `json:"verbs"`
		} `json:"permissions,omitempty"`

		// SupportedProviders SupportedProviders is the list of providers that the backup tool supports.
		SupportedProviders *[]string `json:"supportedProviders,omitempty"`
	} `json:"spec,omitempty"`

	// Status BackupClassStatus defines the status of the BackupClass.
	Status *map[string]interface{} `json:"status,omitempty"`
}

// BackupClassList BackupClassList is an object that contains the list of the existing backupclasss.
type BackupClassList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string        `json:"apiVersion,omitempty"`
	Items      *[]BackupClass `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// BackupList BackupList is an object that contains the list of the existing backups.
type BackupList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string   `json:"apiVersion,omitempty"`
	Items      *[]Backup `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// Instance Instance is the Schema for the instances API.
type Instance struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Spec     *struct {
		// Components Components defines the component instances for this cluster.
		// The keys are component names (e.g., "engine", "proxy", "backupAgent").
		// Which components are valid depends on the selected topology.
		Components *map[string]struct {
			// Config Config specifies the component specific configuration.
			Config *struct {
				// ConfigMapRef LocalObjectReference contains enough information to let you locate the
				// referenced object inside the same namespace.
				ConfigMapRef *struct {
					// Name Name of the referent.
					// This field is effectively required, but due to backwards compatibility is
					// allowed to be empty. Instances of this type with an empty value here are
					// almost certainly wrong.
					// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
					Name *string `json:"name,omitempty"`
				} `json:"configMapRef,omitempty"`
				Key *string `json:"key,omitempty"`

				// SecretRef LocalObjectReference contains enough information to let you locate the
				// referenced object inside the same namespace.
				SecretRef *struct {
					// Name Name of the referent.
					// This field is effectively required, but due to backwards compatibility is
					// allowed to be empty. Instances of this type with an empty value here are
					// almost certainly wrong.
					// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
					Name *string `json:"name,omitempty"`
				} `json:"secretRef,omitempty"`
			} `json:"config,omitempty"`

			// CustomSpec CustomSpec provides an API for customising this component.
			// The API schema is defined by the provider's ComponentSchemas.
			CustomSpec *map[string]interface{} `json:"customSpec,omitempty"`

			// Image Image specifies an override for the image to use.
			// When unspecified, it is autmatically set from the ComponentVersions
			// based on the Version specified.
			Image *string `json:"image,omitempty"`

			// Name Name of the component.
			Name *string `json:"name,omitempty"`

			// Replicas Replicas specifies the number of replicas for this component.
			Replicas *int32 `json:"replicas,omitempty"`

			// Resources Resources requirements for this component.
			Resources *struct {
				Cpu    *Instance_Spec_Components_Resources_Cpu    `json:"cpu,omitempty"`
				Memory *Instance_Spec_Components_Resources_Memory `json:"memory,omitempty"`
			} `json:"resources,omitempty"`

			// Storage Storage requirements for this component.
			// For stateless components, this is an optional field.
			Storage *struct {
				Size         *Instance_Spec_Components_Storage_Size `json:"size,omitempty"`
				StorageClass *string                                `json:"storageClass,omitempty"`
			} `json:"storage,omitempty"`

			// Type Type of the component from the Provider.
			Type *string `json:"type,omitempty"`

			// Version Version of the component from ComponentVersions.
			Version *string `json:"version,omitempty"`
		} `json:"components,omitempty"`

		// Global Global contains provider-level configuration that applies to the entire cluster.
		// The schema for this field is defined by the provider's GlobalSchema.
		Global *map[string]interface{} `json:"global,omitempty"`

		// Provider Provider is the name of the database provider (e.g., "psmdb", "postgresql").
		Provider *string `json:"provider,omitempty"`

		// Topology Topology defines the deployment topology and its configuration.
		Topology *struct {
			// Config Config contains topology-specific configuration.
			// The schema for this field is defined by the provider's TopologyDefinition.
			// Examples: shard count for sharded topology, replication factor, etc.
			Config *map[string]interface{} `json:"config,omitempty"`

			// Type Type is the topology name (e.g., "sharded", "replicaset").
			// The available topologies are defined by the provider.
			// If omitted, the provider's default topology is used.
			Type *string `json:"type,omitempty"`
		} `json:"topology,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		// Components Components is the status of the components in the database cluster.
		Components *[]struct {
			Pods *[]struct {
				// Name Name of the referent.
				// This field is effectively required, but due to backwards compatibility is
				// allowed to be empty. Instances of this type with an empty value here are
				// almost certainly wrong.
				// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
				Name *string `json:"name,omitempty"`
			} `json:"pods,omitempty"`
			Ready *int32  `json:"ready,omitempty"`
			State *string `json:"state,omitempty"`
			Total *int32  `json:"total,omitempty"`
		} `json:"components,omitempty"`

		// ConnectionURL ConnectionURL is the URL to connect to the database cluster.
		ConnectionURL *string `json:"connectionURL,omitempty"`

		// CredentialSecretRef CredentialSecretRef is a reference to the secret containing the credentials.
		// This Secret contains the keys `username` and `password`.
		CredentialSecretRef *struct {
			// Name Name of the referent.
			// This field is effectively required, but due to backwards compatibility is
			// allowed to be empty. Instances of this type with an empty value here are
			// almost certainly wrong.
			// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
			Name *string `json:"name,omitempty"`
		} `json:"credentialSecretRef,omitempty"`

		// Phase Phase of the database cluster.
		Phase *string `json:"phase,omitempty"`
	} `json:"status,omitempty"`
}

// InstanceSpecComponentsResourcesCpu0 defines model for .
type InstanceSpecComponentsResourcesCpu0 = int

// InstanceSpecComponentsResourcesCpu1 defines model for .
type InstanceSpecComponentsResourcesCpu1 = string

// Instance_Spec_Components_Resources_Cpu defines model for Instance.Spec.Components.Resources.Cpu.
type Instance_Spec_Components_Resources_Cpu struct {
	union json.RawMessage
}

// InstanceSpecComponentsResourcesMemory0 defines model for .
type InstanceSpecComponentsResourcesMemory0 = int

// InstanceSpecComponentsResourcesMemory1 defines model for .
type InstanceSpecComponentsResourcesMemory1 = string

// Instance_Spec_Components_Resources_Memory defines model for Instance.Spec.Components.Resources.Memory.
type Instance_Spec_Components_Resources_Memory struct {
	union json.RawMessage
}

// InstanceSpecComponentsStorageSize0 defines model for .
type InstanceSpecComponentsStorageSize0 = int

// InstanceSpecComponentsStorageSize1 defines model for .
type InstanceSpecComponentsStorageSize1 = string

// Instance_Spec_Components_Storage_Size defines model for Instance.Spec.Components.Storage.Size.
type Instance_Spec_Components_Storage_Size struct {
	union json.RawMessage
}

// InstanceList InstanceList is an object that contains the list of the existing instances.
type InstanceList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Items      *[]Instance `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// Provider Provider is the Schema for the providers API.
type Provider struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Spec     *struct {
		ComponentTypes *map[string]struct {
			Versions *[]struct {
				Default *bool   `json:"default,omitempty"`
				Image   *string `json:"image,omitempty"`
				Version *string `json:"version,omitempty"`
			} `json:"versions,omitempty"`
		} `json:"componentTypes,omitempty"`
		Components *map[string]struct {
			Type *string `json:"type,omitempty"`
		} `json:"components,omitempty"`
		Topologies *map[string]struct {
			Components *map[string]struct {
				Optional *bool `json:"optional,omitempty"`
			} `json:"components,omitempty"`
		} `json:"topologies,omitempty"`
	} `json:"spec,omitempty"`
	Status *map[string]interface{} `json:"status,omitempty"`
}

// ProviderList ProviderList is an object that contains the list of the existing providers.
type ProviderList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Items      *[]Provider `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// AsInstanceSpecComponentsResourcesCpu0 returns the union data inside the Instance_Spec_Components_Resources_Cpu as a InstanceSpecComponentsResourcesCpu0
func (t Instance_Spec_Components_Resources_Cpu) AsInstanceSpecComponentsResourcesCpu0() (InstanceSpecComponentsResourcesCpu0, error) {
	var body InstanceSpecComponentsResourcesCpu0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesCpu0 overwrites any union data inside the Instance_Spec_Components_Resources_Cpu as the provided InstanceSpecComponentsResourcesCpu0
func (t *Instance_Spec_Components_Resources_Cpu) FromInstanceSpecComponentsResourcesCpu0(v InstanceSpecComponentsResourcesCpu0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesCpu0 performs a merge with any union data inside the Instance_Spec_Components_Resources_Cpu, using the provided InstanceSpecComponentsResourcesCpu0
func (t *Instance_Spec_Components_Resources_Cpu) MergeInstanceSpecComponentsResourcesCpu0(v InstanceSpecComponentsResourcesCpu0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsResourcesCpu1 returns the union data inside the Instance_Spec_Components_Resources_Cpu as a InstanceSpecComponentsResourcesCpu1
func (t Instance_Spec_Components_Resources_Cpu) AsInstanceSpecComponentsResourcesCpu1() (InstanceSpecComponentsResourcesCpu1, error) {
	var body InstanceSpecComponentsResourcesCpu1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesCpu1 overwrites any union data inside the Instance_Spec_Components_Resources_Cpu as the provided InstanceSpecComponentsResourcesCpu1
func (t *Instance_Spec_Components_Resources_Cpu) FromInstanceSpecComponentsResourcesCpu1(v InstanceSpecComponentsResourcesCpu1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesCpu1 performs a merge with any union data inside the Instance_Spec_Components_Resources_Cpu, using the provided InstanceSpecComponentsResourcesCpu1
func (t *Instance_Spec_Components_Resources_Cpu) MergeInstanceSpecComponentsResourcesCpu1(v InstanceSpecComponentsResourcesCpu1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Resources_Cpu) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Resources_Cpu) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsInstanceSpecComponentsResourcesMemory0 returns the union data inside the Instance_Spec_Components_Resources_Memory as a InstanceSpecComponentsResourcesMemory0
func (t Instance_Spec_Components_Resources_Memory) AsInstanceSpecComponentsResourcesMemory0() (InstanceSpecComponentsResourcesMemory0, error) {
	var body InstanceSpecComponentsResourcesMemory0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesMemory0 overwrites any union data inside the Instance_Spec_Components_Resources_Memory as the provided InstanceSpecComponentsResourcesMemory0
func (t *Instance_Spec_Components_Resources_Memory) FromInstanceSpecComponentsResourcesMemory0(v InstanceSpecComponentsResourcesMemory0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesMemory0 performs a merge with any union data inside the Instance_Spec_Components_Resources_Memory, using the provided InstanceSpecComponentsResourcesMemory0
func (t *Instance_Spec_Components_Resources_Memory) MergeInstanceSpecComponentsResourcesMemory0(v InstanceSpecComponentsResourcesMemory0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsResourcesMemory1 returns the union data inside the Instance_Spec_Components_Resources_Memory as a InstanceSpecComponentsResourcesMemory1
func (t Instance_Spec_Components_Resources_Memory) AsInstanceSpecComponentsResourcesMemory1() (InstanceSpecComponentsResourcesMemory1, error) {
	var body InstanceSpecComponentsResourcesMemory1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesMemory1 overwrites any union data inside the Instance_Spec_Components_Resources_Memory as the provided InstanceSpecComponentsResourcesMemory1
func (t *Instance_Spec_Components_Resources_Memory) FromInstanceSpecComponentsResourcesMemory1(v InstanceSpecComponentsResourcesMemory1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesMemory1 performs a merge with any union data inside the Instance_Spec_Components_Resources_Memory, using the provided InstanceSpecComponentsResourcesMemory1
func (t *Instance_Spec_Components_Resources_Memory) MergeInstanceSpecComponentsResourcesMemory1(v InstanceSpecComponentsResourcesMemory1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Resources_Memory) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Resources_Memory) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsInstanceSpecComponentsStorageSize0 returns the union data inside the Instance_Spec_Components_Storage_Size as a InstanceSpecComponentsStorageSize0
func (t Instance_Spec_Components_Storage_Size) AsInstanceSpecComponentsStorageSize0() (InstanceSpecComponentsStorageSize0, error) {
	var body InstanceSpecComponentsStorageSize0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsStorageSize0 overwrites any union data inside the Instance_Spec_Components_Storage_Size as the provided InstanceSpecComponentsStorageSize0
func (t *Instance_Spec_Components_Storage_Size) FromInstanceSpecComponentsStorageSize0(v InstanceSpecComponentsStorageSize0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsStorageSize0 performs a merge with any union data inside the Instance_Spec_Components_Storage_Size, using the provided InstanceSpecComponentsStorageSize0
func (t *Instance_Spec_Components_Storage_Size) MergeInstanceSpecComponentsStorageSize0(v InstanceSpecComponentsStorageSize0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsStorageSize1 returns the union data inside the Instance_Spec_Components_Storage_Size as a InstanceSpecComponentsStorageSize1
func (t Instance_Spec_Components_Storage_Size) AsInstanceSpecComponentsStorageSize1() (InstanceSpecComponentsStorageSize1, error) {
	var body InstanceSpecComponentsStorageSize1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsStorageSize1 overwrites any union data inside the Instance_Spec_Components_Storage_Size as the provided InstanceSpecComponentsStorageSize1
func (t *Instance_Spec_Components_Storage_Size) FromInstanceSpecComponentsStorageSize1(v InstanceSpecComponentsStorageSize1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsStorageSize1 performs a merge with any union data inside the Instance_Spec_Components_Storage_Size, using the provided InstanceSpecComponentsStorageSize1
func (t *Instance_Spec_Components_Storage_Size) MergeInstanceSpecComponentsStorageSize1(v InstanceSpecComponentsStorageSize1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Storage_Size) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Storage_Size) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
