// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Instance Instance is the Schema for the instances API.
type Instance struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Spec     *struct {
		// Components Components defines the component instances for this cluster.
		// The keys are component names (e.g., "engine", "proxy", "backupAgent").
		// Which components are valid depends on the selected topology.
		Components *map[string]struct {
			// Config Config specifies the component specific configuration.
			Config *struct {
				// ConfigMapRef LocalObjectReference contains enough information to let you locate the
				// referenced object inside the same namespace.
				ConfigMapRef *struct {
					// Name Name of the referent.
					// This field is effectively required, but due to backwards compatibility is
					// allowed to be empty. Instances of this type with an empty value here are
					// almost certainly wrong.
					// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
					Name *string `json:"name,omitempty"`
				} `json:"configMapRef,omitempty"`
				Key *string `json:"key,omitempty"`

				// SecretRef LocalObjectReference contains enough information to let you locate the
				// referenced object inside the same namespace.
				SecretRef *struct {
					// Name Name of the referent.
					// This field is effectively required, but due to backwards compatibility is
					// allowed to be empty. Instances of this type with an empty value here are
					// almost certainly wrong.
					// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
					Name *string `json:"name,omitempty"`
				} `json:"secretRef,omitempty"`
			} `json:"config,omitempty"`

			// CustomSpec CustomSpec provides an API for customising this component.
			// The API schema is defined by the provider's ComponentSchemas.
			CustomSpec *map[string]interface{} `json:"customSpec,omitempty"`

			// Image Image specifies an override for the image to use.
			// When unspecified, it is autmatically set from the ComponentVersions
			// based on the Version specified.
			Image *string `json:"image,omitempty"`

			// Name Name of the component.
			Name *string `json:"name,omitempty"`

			// Replicas Replicas specifies the number of replicas for this component.
			Replicas *int32 `json:"replicas,omitempty"`

			// Resources Resources requirements for this component.
			Resources *struct {
				Cpu    *Instance_Spec_Components_Resources_Cpu    `json:"cpu,omitempty"`
				Memory *Instance_Spec_Components_Resources_Memory `json:"memory,omitempty"`
			} `json:"resources,omitempty"`

			// Storage Storage requirements for this component.
			// For stateless components, this is an optional field.
			Storage *struct {
				Size         *Instance_Spec_Components_Storage_Size `json:"size,omitempty"`
				StorageClass *string                                `json:"storageClass,omitempty"`
			} `json:"storage,omitempty"`

			// Type Type of the component from the Provider.
			Type *string `json:"type,omitempty"`

			// Version Version of the component from ComponentVersions.
			Version *string `json:"version,omitempty"`
		} `json:"components,omitempty"`

		// Global Global contains provider-level configuration that applies to the entire cluster.
		// The schema for this field is defined by the provider's GlobalSchema.
		Global *map[string]interface{} `json:"global,omitempty"`

		// Provider Provider is the name of the database provider (e.g., "psmdb", "postgresql").
		Provider *string `json:"provider,omitempty"`

		// Topology Topology defines the deployment topology and its configuration.
		Topology *struct {
			// Config Config contains topology-specific configuration.
			// The schema for this field is defined by the provider's TopologyDefinition.
			// Examples: shard count for sharded topology, replication factor, etc.
			Config *map[string]interface{} `json:"config,omitempty"`

			// Type Type is the topology name (e.g., "sharded", "replicaset").
			// The available topologies are defined by the provider.
			// If omitted, the provider's default topology is used.
			Type *string `json:"type,omitempty"`
		} `json:"topology,omitempty"`
	} `json:"spec,omitempty"`
	Status *struct {
		// Components Components is the status of the components in the database cluster.
		Components *[]struct {
			Pods *[]struct {
				// Name Name of the referent.
				// This field is effectively required, but due to backwards compatibility is
				// allowed to be empty. Instances of this type with an empty value here are
				// almost certainly wrong.
				// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
				Name *string `json:"name,omitempty"`
			} `json:"pods,omitempty"`
			Ready *int32  `json:"ready,omitempty"`
			State *string `json:"state,omitempty"`
			Total *int32  `json:"total,omitempty"`
		} `json:"components,omitempty"`

		// ConnectionURL ConnectionURL is the URL to connect to the database cluster.
		ConnectionURL *string `json:"connectionURL,omitempty"`

		// CredentialSecretRef CredentialSecretRef is a reference to the secret containing the credentials.
		// This Secret contains the keys `username` and `password`.
		CredentialSecretRef *struct {
			// Name Name of the referent.
			// This field is effectively required, but due to backwards compatibility is
			// allowed to be empty. Instances of this type with an empty value here are
			// almost certainly wrong.
			// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
			Name *string `json:"name,omitempty"`
		} `json:"credentialSecretRef,omitempty"`

		// Phase Phase of the database cluster.
		Phase *string `json:"phase,omitempty"`
	} `json:"status,omitempty"`
}

// InstanceSpecComponentsResourcesCpu0 defines model for .
type InstanceSpecComponentsResourcesCpu0 = int

// InstanceSpecComponentsResourcesCpu1 defines model for .
type InstanceSpecComponentsResourcesCpu1 = string

// Instance_Spec_Components_Resources_Cpu defines model for Instance.Spec.Components.Resources.Cpu.
type Instance_Spec_Components_Resources_Cpu struct {
	union json.RawMessage
}

// InstanceSpecComponentsResourcesMemory0 defines model for .
type InstanceSpecComponentsResourcesMemory0 = int

// InstanceSpecComponentsResourcesMemory1 defines model for .
type InstanceSpecComponentsResourcesMemory1 = string

// Instance_Spec_Components_Resources_Memory defines model for Instance.Spec.Components.Resources.Memory.
type Instance_Spec_Components_Resources_Memory struct {
	union json.RawMessage
}

// InstanceSpecComponentsStorageSize0 defines model for .
type InstanceSpecComponentsStorageSize0 = int

// InstanceSpecComponentsStorageSize1 defines model for .
type InstanceSpecComponentsStorageSize1 = string

// Instance_Spec_Components_Storage_Size defines model for Instance.Spec.Components.Storage.Size.
type Instance_Spec_Components_Storage_Size struct {
	union json.RawMessage
}

// InstanceList InstanceList is an object that contains the list of the existing instances.
type InstanceList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Items      *[]Instance `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// Provider Provider is the Schema for the providers API.
type Provider struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Spec     *struct {
		ComponentTypes *map[string]struct {
			Versions *[]struct {
				Default *bool   `json:"default,omitempty"`
				Image   *string `json:"image,omitempty"`
				Version *string `json:"version,omitempty"`
			} `json:"versions,omitempty"`
		} `json:"componentTypes,omitempty"`
		Components *map[string]struct {
			Type *string `json:"type,omitempty"`
		} `json:"components,omitempty"`
		Topologies *map[string]struct {
			Components *map[string]struct {
				Optional *bool `json:"optional,omitempty"`
			} `json:"components,omitempty"`
		} `json:"topologies,omitempty"`
	} `json:"spec,omitempty"`
	Status *map[string]interface{} `json:"status,omitempty"`
}

// ProviderList ProviderList is an object that contains the list of the existing providers.
type ProviderList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Items      *[]Provider `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// AsInstanceSpecComponentsResourcesCpu0 returns the union data inside the Instance_Spec_Components_Resources_Cpu as a InstanceSpecComponentsResourcesCpu0
func (t Instance_Spec_Components_Resources_Cpu) AsInstanceSpecComponentsResourcesCpu0() (InstanceSpecComponentsResourcesCpu0, error) {
	var body InstanceSpecComponentsResourcesCpu0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesCpu0 overwrites any union data inside the Instance_Spec_Components_Resources_Cpu as the provided InstanceSpecComponentsResourcesCpu0
func (t *Instance_Spec_Components_Resources_Cpu) FromInstanceSpecComponentsResourcesCpu0(v InstanceSpecComponentsResourcesCpu0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesCpu0 performs a merge with any union data inside the Instance_Spec_Components_Resources_Cpu, using the provided InstanceSpecComponentsResourcesCpu0
func (t *Instance_Spec_Components_Resources_Cpu) MergeInstanceSpecComponentsResourcesCpu0(v InstanceSpecComponentsResourcesCpu0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsResourcesCpu1 returns the union data inside the Instance_Spec_Components_Resources_Cpu as a InstanceSpecComponentsResourcesCpu1
func (t Instance_Spec_Components_Resources_Cpu) AsInstanceSpecComponentsResourcesCpu1() (InstanceSpecComponentsResourcesCpu1, error) {
	var body InstanceSpecComponentsResourcesCpu1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesCpu1 overwrites any union data inside the Instance_Spec_Components_Resources_Cpu as the provided InstanceSpecComponentsResourcesCpu1
func (t *Instance_Spec_Components_Resources_Cpu) FromInstanceSpecComponentsResourcesCpu1(v InstanceSpecComponentsResourcesCpu1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesCpu1 performs a merge with any union data inside the Instance_Spec_Components_Resources_Cpu, using the provided InstanceSpecComponentsResourcesCpu1
func (t *Instance_Spec_Components_Resources_Cpu) MergeInstanceSpecComponentsResourcesCpu1(v InstanceSpecComponentsResourcesCpu1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Resources_Cpu) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Resources_Cpu) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsInstanceSpecComponentsResourcesMemory0 returns the union data inside the Instance_Spec_Components_Resources_Memory as a InstanceSpecComponentsResourcesMemory0
func (t Instance_Spec_Components_Resources_Memory) AsInstanceSpecComponentsResourcesMemory0() (InstanceSpecComponentsResourcesMemory0, error) {
	var body InstanceSpecComponentsResourcesMemory0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesMemory0 overwrites any union data inside the Instance_Spec_Components_Resources_Memory as the provided InstanceSpecComponentsResourcesMemory0
func (t *Instance_Spec_Components_Resources_Memory) FromInstanceSpecComponentsResourcesMemory0(v InstanceSpecComponentsResourcesMemory0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesMemory0 performs a merge with any union data inside the Instance_Spec_Components_Resources_Memory, using the provided InstanceSpecComponentsResourcesMemory0
func (t *Instance_Spec_Components_Resources_Memory) MergeInstanceSpecComponentsResourcesMemory0(v InstanceSpecComponentsResourcesMemory0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsResourcesMemory1 returns the union data inside the Instance_Spec_Components_Resources_Memory as a InstanceSpecComponentsResourcesMemory1
func (t Instance_Spec_Components_Resources_Memory) AsInstanceSpecComponentsResourcesMemory1() (InstanceSpecComponentsResourcesMemory1, error) {
	var body InstanceSpecComponentsResourcesMemory1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesMemory1 overwrites any union data inside the Instance_Spec_Components_Resources_Memory as the provided InstanceSpecComponentsResourcesMemory1
func (t *Instance_Spec_Components_Resources_Memory) FromInstanceSpecComponentsResourcesMemory1(v InstanceSpecComponentsResourcesMemory1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesMemory1 performs a merge with any union data inside the Instance_Spec_Components_Resources_Memory, using the provided InstanceSpecComponentsResourcesMemory1
func (t *Instance_Spec_Components_Resources_Memory) MergeInstanceSpecComponentsResourcesMemory1(v InstanceSpecComponentsResourcesMemory1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Resources_Memory) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Resources_Memory) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsInstanceSpecComponentsStorageSize0 returns the union data inside the Instance_Spec_Components_Storage_Size as a InstanceSpecComponentsStorageSize0
func (t Instance_Spec_Components_Storage_Size) AsInstanceSpecComponentsStorageSize0() (InstanceSpecComponentsStorageSize0, error) {
	var body InstanceSpecComponentsStorageSize0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsStorageSize0 overwrites any union data inside the Instance_Spec_Components_Storage_Size as the provided InstanceSpecComponentsStorageSize0
func (t *Instance_Spec_Components_Storage_Size) FromInstanceSpecComponentsStorageSize0(v InstanceSpecComponentsStorageSize0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsStorageSize0 performs a merge with any union data inside the Instance_Spec_Components_Storage_Size, using the provided InstanceSpecComponentsStorageSize0
func (t *Instance_Spec_Components_Storage_Size) MergeInstanceSpecComponentsStorageSize0(v InstanceSpecComponentsStorageSize0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsStorageSize1 returns the union data inside the Instance_Spec_Components_Storage_Size as a InstanceSpecComponentsStorageSize1
func (t Instance_Spec_Components_Storage_Size) AsInstanceSpecComponentsStorageSize1() (InstanceSpecComponentsStorageSize1, error) {
	var body InstanceSpecComponentsStorageSize1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsStorageSize1 overwrites any union data inside the Instance_Spec_Components_Storage_Size as the provided InstanceSpecComponentsStorageSize1
func (t *Instance_Spec_Components_Storage_Size) FromInstanceSpecComponentsStorageSize1(v InstanceSpecComponentsStorageSize1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsStorageSize1 performs a merge with any union data inside the Instance_Spec_Components_Storage_Size, using the provided InstanceSpecComponentsStorageSize1
func (t *Instance_Spec_Components_Storage_Size) MergeInstanceSpecComponentsStorageSize1(v InstanceSpecComponentsStorageSize1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Storage_Size) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Storage_Size) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
