name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: "--max_old_space_size=4096"
  GONOPROXY: 'github.com/percona'
  GONOSUMDB: 'github.com/percona'
  GOPRIVATE: 'github.com/percona'
  REGISTRY: ghcr.io

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_PREFIX: 'ghcr.io/openeverest'
      EVEREST_SERVER_DEV_IMAGE_NAME: 'openeverest-dev'
      EVEREST_CTL_DEV_IMAGE_NAME: 'everestctl-dev'
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          lfs: true
          ref: "main"

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        with:
          version: 9.4.0

      - name: Run with Node 20
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Build Everest Frontend app
        run: |
          cd ui
          pnpm install
          EVEREST_OUT_DIR=${GITHUB_WORKSPACE}/public/dist/ pnpm build

      - name: Set up Go release
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build Everest
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build

      - name: Setup docker build metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        id: meta
        with:
          images: ${{ env.IMAGE_PREFIX }}/${{ env.EVEREST_SERVER_DEV_IMAGE_NAME }}
          tags: 0.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push openeverest dev image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Setup docker build metadata for everestctl
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        id: everestctl_meta
        with:
          images: ${{ env.IMAGE_PREFIX }}/${{ env.EVEREST_CTL_DEV_IMAGE_NAME }}
          tags: 0.0.0

      - name: Build and Push everestctl dev image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          file: Dockerfile.everestctl
          push: true
          tags: ${{ steps.everestctl_meta.outputs.tags }}

