---
name: Release helmtools Docker image
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for the image"
        required: true
      kubectl_version:
        description: "Version of kubectl to use"
        required: false
        default: "v1.33.5"
permissions:
  contents: read

jobs:
  release:
     env:
      IMG_OWNER: percona
      IMG_NAME: everest-helmtools
      VERSION: ${{ github.event.inputs.version }}
      KUBECTL_VERSION: ${{ github.event.inputs.kubectl_version }}

     runs-on: ubuntu-latest
     steps:
      - name: Check out code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          repository: percona/everest
          path: everest
          token: ${{ secrets.ROBOT_TOKEN }}
          sparse-checkout: |
            Dockerfile.helmtools

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        name: Build & push Docker image
        with:
          context: everest
          push: true
          tags: ${{ env.IMG_OWNER }}/${{ env.IMG_NAME }}:${{ env.VERSION }}
          file: everest/Dockerfile.helmtools
          build-args: |
            KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
