package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

func main() {
	crdDir := flag.String("crd-dir", "config/crd/bases", "Directory containing CRD YAML manifests")
	outputFile := flag.String("output", "docs/spec/crds.openapi.gen.yml", "Output OpenAPI YAML file")
	flag.Parse()

	if err := run(*crdDir, *outputFile); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(crdDir, outputFile string) error {
	crdFiles, err := filepath.Glob(filepath.Join(crdDir, "*.yaml"))
	if err != nil {
		return fmt.Errorf("failed to find CRD files: %w", err)
	}

	if len(crdFiles) == 0 {
		return fmt.Errorf("no CRD files found in %s", crdDir)
	}

	schemas := make(map[string]*openapi3.SchemaRef)
	for _, crdFile := range crdFiles {
		if err := extractSchemas(crdFile, schemas); err != nil {
			return fmt.Errorf("failed to extract schemas from %s: %w", crdFile, err)
		}
	}

	spec := &openapi3.T{
		OpenAPI: "3.0.2",
		Info: &openapi3.Info{
			Title:       "OpenEverest CRD Schemas",
			Version:     "1.0.0",
			Description: "OpenAPI schemas extracted from Kubernetes CRD manifests. This file is auto-generated - do not edit manually.",
		},
		Components: &openapi3.Components{
			Schemas: schemas,
		},
	}

	yamlData, err := yaml.Marshal(spec)
	if err != nil {
		return fmt.Errorf("failed to marshal OpenAPI spec: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outputFile), 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	header := "# Code generated by gen-crd-schemas. DO NOT EDIT.\n\n"
	out := append([]byte(header), yamlData...)

	if err := os.WriteFile(outputFile, out, 0o644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	fmt.Printf("Successfully extracted %d schemas to %s\n", len(schemas), outputFile)
	return nil
}

func extractSchemas(crdFile string, schemas map[string]*openapi3.SchemaRef) error {
	data, err := os.ReadFile(crdFile)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}

	var crd apiextensionsv1.CustomResourceDefinition
	if err := yaml.Unmarshal(data, &crd); err != nil {
		return fmt.Errorf("failed to unmarshal CRD: %w", err)
	}

	for _, version := range crd.Spec.Versions {
		if version.Schema == nil || version.Schema.OpenAPIV3Schema == nil {
			continue
		}

		kind := crd.Spec.Names.Kind
		if kind == "" {
			continue
		}

		// Convert CRD schema to openapi3.Schema using JSON for efficient type conversion
		schemaBytes, err := json.Marshal(version.Schema.OpenAPIV3Schema)
		if err != nil {
			return fmt.Errorf("failed to marshal schema: %w", err)
		}

		schema := &openapi3.Schema{}
		if err := json.Unmarshal(schemaBytes, schema); err != nil {
			return fmt.Errorf("failed to unmarshal to openapi3.Schema: %w", err)
		}

		// Add description if missing
		if schema.Description == "" {
			schema.Description = fmt.Sprintf("%s is the Schema for the %s API.", kind, crd.Spec.Names.Plural)
		}

		schemas[kind] = openapi3.NewSchemaRef("", schema)

		listKind := crd.Spec.Names.ListKind
		if listKind == "" {
			listKind = kind + "List"
		}

		listSchema := &openapi3.Schema{
			Type:        &openapi3.Types{"object"},
			Description: fmt.Sprintf("%s is an object that contains the list of the existing %s.", listKind, strings.ToLower(kind)+"s"),
			Properties: openapi3.Schemas{
				"apiVersion": openapi3.NewSchemaRef("", &openapi3.Schema{
					Type:        &openapi3.Types{"string"},
					Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
				}),
				"kind": openapi3.NewSchemaRef("", &openapi3.Schema{
					Type:        &openapi3.Types{"string"},
					Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
				}),
				"items": openapi3.NewSchemaRef("", &openapi3.Schema{
					Type:  &openapi3.Types{"array"},
					Items: openapi3.NewSchemaRef(fmt.Sprintf("#/components/schemas/%s", kind), nil),
				}),
				"metadata": openapi3.NewSchemaRef("", &openapi3.Schema{
					Type: &openapi3.Types{"object"},
				}),
			},
		}

		schemas[listKind] = openapi3.NewSchemaRef("", listSchema)

		fmt.Printf("  Extracted schema for %s (version %s) from %s\n", kind, version.Name, filepath.Base(crdFile))
	}

	return nil
}
